### PR TITLE
Update Java to v17

### PR DESCRIPTION
**Pull request by Genyus**

### CODE REVIEW

**Review by tanyapowell — COMMENTED** [review]
Has this been tested?

**Comment by Genyus** [comment]
I tested a number of packages without issue, but I couldn't reproduce the reported output on my system to begin with, so that's not necessarily a solid benchmark

**Review by sohbaker — CHANGES_REQUESTED** [review]
Looks like the `getting-started` and `web-applications` folders are missing from this update.

**Comment by Genyus** [comment]
@sohbaker Those folders had no references to Java 11. But while checking, found and fixed references to Java SE 8, so thanks. 🙂

**Comment by sohbaker** [comment]
All good. The PR said update to 17 so when they weren't listed I wondered whether they would have needed updating.

**Comment by sohbaker** [comment]
(Hit the wrong button whilst adding a comment)

**Review by sohbaker — APPROVED** [review]
LGTM

**Pull request merged**
